extensions:
  languageService:
    cacheSchemaFileForLookup: true
projects:
  projects:
    schema:
      - https://api.github.com/graphql:
        headers:
          Authorization: Bearer ${REACT_APP_GITHUB_TOKEN}
    documents: src/projects/api/**/*.{graphql,tsx,jsx,ts,js}
